#
# Copyright (C) 2026 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#
# Values marked [V] were re-derived from Advan stock firmware
# ADVAN_6781_S34NF2_V4.0_20250304 (build 1741067669) and/or its images.
# Values marked [C] are carried forward and still want an independent check
# -- see notes/JOURNAL.md for status. There is no live device on this
# project; [C] items are verified by tester-run gates, never assumed.
#

DEVICE_PATH := device/advan/6781

# A/B
AB_OTA_UPDATER := true
AB_OTA_PARTITIONS += \
    boot \
    dtbo \
    odm_dlkm \
    product \
    system \
    system_ext \
    vbmeta \
    vbmeta_system \
    vbmeta_vendor \
    vendor \
    vendor_boot \
    vendor_dlkm

# Architecture                                                          [V]
# Helio G100 (MT6789H): 2x Cortex-A76 + 6x Cortex-A55, confirmed via the
# stock dtb's cpu compatibles (arm,cortex-a76 + arm,cortex-a55).
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-2a-dotprod
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := cortex-a76
TARGET_CPU_VARIANT_RUNTIME := cortex-a76

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-2a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a55
TARGET_2ND_CPU_VARIANT_RUNTIME := cortex-a55

TARGET_BOARD_SUFFIX := _64
TARGET_USES_64_BIT_BINDER := true

# Bootloader                                                            [V/C]
# Platform mt6789 [V]: stock scatter (MT6789/k6789v1_64), stock dtb
# (mediatek,MT6789 + androidboot.hardware=mt6789), RS4 journal variant
# table (G100 = MT6789H). Board name 6781 [C]: the operator-decided
# codename; stock's own ro.product.board is the generic MTK project name
# (pri_board) and is not usable here. Tester gate: `getprop ro.product.board`.
TARGET_BOOTLOADER_BOARD_NAME := 6781
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := mt6789

# Kernel -- GKI. This device ships a PREBUILT kernel image; the ROM does not
# compile it. See device/advan/6781-kernel.                             [V]
BOARD_USES_GENERIC_KERNEL_IMAGE := true
BOARD_KERNEL_IMAGE_NAME := Image.gz
BOARD_RAMDISK_USE_LZ4 := true
BOARD_BOOT_HEADER_VERSION := 4
BOARD_KERNEL_PAGESIZE := 4096

# Stock boot.img ships an EMPTY cmdline (unpack_bootimg, measured); the one
# boot parameter lives in vendor_boot's cmdline field. That is also what the
# build does with this variable at header v4 -- BOARD_KERNEL_CMDLINE is
# passed as --vendor_cmdline, not into boot.img -- so setting it here
# reproduces stock. Everything else the kernel sees
# (androidboot.hardware=mt6789 &c.) is appended by the MediaTek LK at boot,
# not stored in any image we build.
#
# There is deliberately no androidboot.selinux=permissive here: this tree
# runs enforcing.                                                     [V]
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2

# Offsets                                                               [C]
# kernel_addr 0x40000000 and ramdisk_addr 0x66f00000 read back from the
# stock vendor_boot header (v4, page 4096) and reconstruct exactly from the
# MT6789 reference base + offsets below (base+kernel_offset,
# base+ramdisk_offset). tags/dtb addrs are the same reference set; the
# first bootable build (tester-run) is what promotes this block to [V].
BOARD_KERNEL_BASE := 0x3fff8000
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x26f08000
BOARD_KERNEL_TAGS_OFFSET := 0x07c88000
BOARD_DTB_OFFSET := 0x07c88000

BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)
BOARD_MKBOOTIMG_ARGS += --base $(BOARD_KERNEL_BASE)
BOARD_MKBOOTIMG_ARGS += --kernel_offset $(BOARD_KERNEL_OFFSET)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS += --dtb_offset $(BOARD_DTB_OFFSET)
BOARD_MKBOOTIMG_ARGS += --pagesize $(BOARD_KERNEL_PAGESIZE)

# Kernel -- built FROM SOURCE, with prebuilt dtb/dtbo/modules alongside.
#
# Only the Image is compiled. The dtb, dtbo and all vendor modules (180
# vendor_dlkm + 178 vendor_boot first-stage) remain MediaTek/Advan prebuilts:
# they are not part of GKI and there is no source for them.
#
# SINGLE SOURCE OF TRUTH for the config: 6781_defconfig lives in the kernel
# source repo at arch/arm64/configs/, is generated by the kernel project's
# build.sh (stock.config + performance + network + bore + ntsync, merged and
# olddefconfig'd) and committed there. Both the kernel project and this ROM
# build read that one file, so they cannot drift.
#
# Do NOT pass a list here. LineageOS documents TARGET_KERNEL_CONFIG as "list
# of defconfigs, first being the base", but make-kernel-config passes them
# straight to Kbuild as make targets -- and stock GKI Kbuild runs them
# sequentially, last one winning, with no merge. A list would silently build
# the wrong config.
#
# gki_defconfig does NOT work: the config is what fixes the symbol CRCs, so
# a wrong defconfig yields a kernel that builds fine and boots nothing.
#
# Never set KERNEL_LTO. kernel.mk honours it (thin/full/none) by rewriting
# LTO_CLANG_FULL after the defconfig is applied -- which changes
# module_layout and breaks every vendor module.
TARGET_KERNEL_PACKAGE := device/advan/6781-kernel
TARGET_KERNEL_SOURCE := kernel/advan/6781
TARGET_KERNEL_CONFIG := 6781_defconfig
TARGET_KERNEL_CLANG_COMPILE := true
TARGET_KERNEL_CLANG_VERSION := r416183b

# CROSS_COMPILE must be passed even though this kernel is built entirely with
# clang, and getting that wrong does NOT fail the build -- it silently
# produces a kernel that cannot load a single vendor module. (Full mechanism
# documented in the RS4 tree's BoardConfig.mk: clang assembles for the HOST,
# Kconfig's arm64 probes fail, KASAN_GENERIC is picked, LTO/CFI vanish, and
# module_layout 0x7c24b32d is lost while the defconfig looks correct.)
#
# aarch64-linux-gnu- (not the aarch64-linux-android- default) matches the
# toolchain triple the KMI-verified kernel was built with.
TARGET_KERNEL_NO_GCC := false
TARGET_KERNEL_CROSS_COMPILE_PREFIX := aarch64-linux-gnu-
# NOTE the '=' -- this MUST be a recursively-expanded assignment. BUILD_TOP
# is not defined yet when BoardConfig.mk is parsed, so ':=' bakes in an
# empty prefix and the kernel dies at its first host tool with
# "/bin/sh: 1: clang: not found".
TARGET_KERNEL_CLANG_PATH = $(BUILD_TOP)/prebuilts/clang/kernel/linux-x86/clang-r416183b
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64

BOARD_PREBUILT_DTBOIMAGE := $(TARGET_KERNEL_PACKAGE)/dtbo.img
BOARD_PREBUILT_DTBIMAGE_DIR := $(TARGET_KERNEL_PACKAGE)/dtb
BOARD_INCLUDE_DTB_IN_BOOTIMG := true

# KMI gate inputs (see Android.mk and kmi-check.py).                    [V]
#
# Every prebuilt vendor module on this device is version-checked at load
# time against whatever kernel is built, and the set includes storage,
# display and the GPU -- so a kernel whose symbol CRCs disagree does not
# boot, and does not fail to BUILD either. The gate exists for that reason.
#
# 0x7c24b32d across all 180/180 zip-chained stock vendor_dlkm modules
# (measured 2026-09-19), reproduced by CFI_CLANG=y + LTO_CLANG_FULL=y +
# MODVERSIONS=y from MediaTek's shipping config. The same KMI covers both
# module sets, so one kernel satisfies all 358.
BOARD_KMI_MODULE_LAYOUT := 0x7c24b32d
KMI_VENDOR_MODULES_DIR := $(TARGET_KERNEL_PACKAGE)/modules/vendor_dlkm
KMI_RAMDISK_MODULES_DIR := $(TARGET_KERNEL_PACKAGE)/modules/vendor_boot

# OPTIONAL: ship a kernel built by the separate custom-kernel project
# (itel-rs4-kernel, vanilla variant -- the S666LN's kernel; operator
# decision 2026-09-29) instead of compiling the GKI source in this tree.
# Run import-kernel.sh to populate this; absent it, the tree builds from
# source. (Same shape as the RS4 tree's S666LN_CUSTOM_KERNEL block; see
# Android.mk for how KMI_SYMVERS follows the import.)
6781_CUSTOM_KERNEL := $(wildcard $(TARGET_KERNEL_PACKAGE)/prebuilt/Image.gz)
ifneq ($(6781_CUSTOM_KERNEL),)
    TARGET_PREBUILT_KERNEL := $(6781_CUSTOM_KERNEL)
    TARGET_FORCE_PREBUILT_KERNEL := true
    KMI_SYMVERS := $(TARGET_KERNEL_PACKAGE)/prebuilt/vmlinux.symvers
endif

# Kernel modules. _LOAD is mandatory: if left unset the build defaults it to
# the FULL module list, and neither partition loads all of what it carries
# (vendor_dlkm ships 180 and loads 159; vendor_boot ships 178 and loads 161).
# Orders are stock's, recovered from the zip-chained vendor_boot ramdisk and
# vendor_dlkm image (modules.load / modules.load.recovery, 2026-09-19).
# A wrong order is a watchdog reset ~5 s into boot (LK arms the HW watchdog
# before jumping to the kernel; a late watchdog driver never probes): no
# panic, no logcat, no USB -- the RS4 build-19 lesson, applied here by
# construction since these lists ARE stock's.
BOARD_VENDOR_RAMDISK_KERNEL_MODULES := \
    $(wildcard $(KMI_RAMDISK_MODULES_DIR)/*.ko)
BOARD_VENDOR_KERNEL_MODULES := \
    $(wildcard $(KMI_VENDOR_MODULES_DIR)/*.ko)

# Read the orders from the lists that ship beside the .ko files rather than
# copying hundreds of module names in here, so the two cannot drift. _LOAD
# takes full paths and must be a subset of _MODULES above; the build writes
# $(notdir) of each into modules.load, in this order. Stock's lists use bare
# filenames, which addprefix resolves against the module dirs.
BOARD_VENDOR_RAMDISK_KERNEL_MODULES_LOAD := \
    $(addprefix $(KMI_RAMDISK_MODULES_DIR)/,\
        $(shell cat $(KMI_RAMDISK_MODULES_DIR)/modules.load))
BOARD_VENDOR_RAMDISK_RECOVERY_KERNEL_MODULES_LOAD := \
    $(addprefix $(KMI_RAMDISK_MODULES_DIR)/,\
        $(shell cat $(KMI_RAMDISK_MODULES_DIR)/modules.load.recovery))
BOARD_VENDOR_KERNEL_MODULES_LOAD := \
    $(addprefix $(KMI_VENDOR_MODULES_DIR)/,\
        $(shell cat $(KMI_VENDOR_MODULES_DIR)/modules.load))

# A missing or unreadable list expands to nothing, which is indistinguishable
# from never setting _LOAD at all -- i.e. silently back to the watchdog bug.
# Fail the build instead.
ifeq ($(strip $(BOARD_VENDOR_RAMDISK_KERNEL_MODULES_LOAD)),)
    $(error 6781: $(KMI_RAMDISK_MODULES_DIR)/modules.load is missing or empty)
endif
ifeq ($(strip $(BOARD_VENDOR_RAMDISK_RECOVERY_KERNEL_MODULES_LOAD)),)
    $(error 6781: $(KMI_RAMDISK_MODULES_DIR)/modules.load.recovery is missing or empty)
endif
ifeq ($(strip $(BOARD_VENDOR_KERNEL_MODULES_LOAD)),)
    $(error 6781: $(KMI_VENDOR_MODULES_DIR)/modules.load is missing or empty)
endif

# Recovery lives in vendor_boot; there is no dedicated recovery partition
# (stock scatter carries none). [V]
# BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT is what actually enables
# BUILDING_RECOVERY_IMAGE for this layout; TARGET_RECOVERY_FSTAB is
# load-bearing for the OTA ZIP (without it INTERNAL_OTA_PACKAGE_TARGET goes
# empty and `bacon` fails 3000 lines later with "mv: Needs 2 arguments").
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/rootdir/etc/fstab.mt6789

BOARD_USES_RECOVERY_AS_BOOT :=
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true
BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT := true
TARGET_NO_RECOVERY := true
BOARD_EXCLUDE_KERNEL_FROM_RECOVERY_IMAGE := true

# Partition sizes                                                       [V]
# super 9663676416 B (scatter 0x240000000); group `main` max 9661579264 B,
# slot A content ~6.5 GB -- all read back from the stock super metadata
# (lpparse.py, 2026-09-19). The group name here is `main`, NOT
# mtk_dynamic_partitions: that is what stock declares.
BOARD_FLASH_BLOCK_SIZE := 262144
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864
# 8 MiB (scatter dtbo_a 0x800000; stock dtbo.img is exactly this).
# A wrong value here passes every build-time check and fails only at flash
# time with No space left on device (RS4 lesson) -- verified against the
# scatter AND the image, not one of them.
BOARD_DTBOIMG_PARTITION_SIZE := 8388608

BOARD_SUPER_PARTITION_SIZE := 9663676416
BOARD_SUPER_PARTITION_GROUPS := main

# Group max is the STOCK max, deliberately: it is a compatibility ceiling,
# not a fidelity value. RS4's lowering (8 GiB -> 4 GiB) was measured against
# a second on-device geometry that does not exist here, so repeating it
# would be fabrication. Sideload-via-stub-recovery cannot fit ~6.5 GB of
# content into half-super either way -- that needs a snapshot-capable
# recovery and is a tester-validated constraint (see notes/JOURNAL.md),
# not something a smaller number here would fix.
BOARD_MAIN_SIZE := 9661579264
BOARD_MAIN_PARTITION_LIST := \
    odm_dlkm \
    product \
    system \
    system_ext \
    vendor \
    vendor_dlkm

# Filesystems -- stock ships ext4 on ALL six logical partitions (measured
# per-image: erofs magic absent, ext4 magic present, debugfs lists
# directories). There is no erofs on this device, so no compressor block.
TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_PRODUCT := product
TARGET_COPY_OUT_SYSTEM_EXT := system_ext
TARGET_COPY_OUT_ODM_DLKM := odm_dlkm
TARGET_COPY_OUT_VENDOR_DLKM := vendor_dlkm

BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEM_EXTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_ODM_DLKMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDOR_DLKMIMAGE_FILE_SYSTEM_TYPE := ext4

TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

# Vendor security patch level. THIS IS LOAD-BEARING; it is not cosmetic.
# Without it ro.vendor.build.security_patch ships EMPTY and the Trustonic
# KeyMint TA stays unconfigured (error -49), vold cannot mint the metadata
# key, /data cannot be prepared, and init reboots to recovery -- presenting
# as a bootloop. 2025-02-05 is what THIS stock ships. It must match stock
# rather than PLATFORM_SECURITY_PATCH, because the vendor blobs ARE that
# stock build.                                                       [V]
VENDOR_SECURITY_PATCH := 2025-02-05

# Metadata / Virtual A/B                                                [V]
# (stock metadata partition 32 MiB; ro.virtual_ab.enabled=true in stock
# vendor props.) Only the BOARD_* half belongs here; PRODUCT_USE_DYNAMIC_
# PARTITIONS and PRODUCT_VIRTUAL_AB_OTA are product variables and live in
# device.mk (assigning them here fails with "cannot assign to readonly
# variable").
BOARD_USES_METADATA_PARTITION := true

# AVB. The stock chain (SHA256_RSA2048, rollback 0, flags 0x0, main vbmeta
# chaining vbmeta_system + vbmeta_vendor -- measured 2026-09-19) is signed
# with the public AOSP test key, so this offers no real protection; it is
# kept as-is so verified boot stays green. Real signing keys are a ROM
# decision and belong in the build recipe, not here.                 [C]
# VBMETA_SYSTEM/VENDOR coverage (product+system+system_ext / vendor) is the
# RS4-measured shape; the Advan per-image coverage is UNREAD, so a wrong
# list here must fail packaging LOUDLY at build time -- that is the
# verifier, and this block stays [C] until a build passes with it.
BOARD_AVB_ENABLE := true
BOARD_AVB_ALGORITHM := SHA256_RSA2048
BOARD_AVB_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem
BOARD_AVB_ROLLBACK_INDEX := 1
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 2
BOARD_AVB_VBMETA_SYSTEM := product system system_ext
BOARD_AVB_VBMETA_SYSTEM_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem
BOARD_AVB_VBMETA_SYSTEM_ALGORITHM := SHA256_RSA2048
BOARD_AVB_VBMETA_SYSTEM_ROLLBACK_INDEX := $(PLATFORM_SECURITY_PATCH_TIMESTAMP)
BOARD_AVB_VBMETA_SYSTEM_ROLLBACK_INDEX_LOCATION := 2

BOARD_AVB_VBMETA_VENDOR := vendor
BOARD_AVB_VBMETA_VENDOR_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem
BOARD_AVB_VBMETA_VENDOR_ALGORITHM := SHA256_RSA2048
BOARD_AVB_VBMETA_VENDOR_ROLLBACK_INDEX := $(PLATFORM_SECURITY_PATCH_TIMESTAMP)
BOARD_AVB_VBMETA_VENDOR_ROLLBACK_INDEX_LOCATION := 4

# Display                                                              [C]
# Stock declares ro.sf.lcd_density=480 in the generic MGVI section and
# nowhere else -- the same untrustworthy class as RS4 stock (which resolved
# to a 240dp-wide screen for a 720px panel). 440 is an FHD+-class
# placeholder, NOT a measurement. Tester gate before release: `wm density`
# on STOCK (reported by a tester holding the device) + physical
# measurement; this line is corrected to that, never "tuned".
TARGET_SCREEN_DENSITY := 440

# OTA device assert -- PIN pre-device to the codename.
# (RS4 mechanism, same branch: releasetools resolves ro.product.device
# through ro.product.property_source_order, so without this the identity
# fix silently rewrites pre-device and locks out older recoveries.)
# Single value, not a list: pre-device is a join of this variable.
TARGET_OTA_ASSERT_DEVICE := 6781

# Properties -- a value containing a space must be set through these raw
# .prop files, not PRODUCT_*_PROPERTIES.
TARGET_SYSTEM_PROP += $(DEVICE_PATH)/configs/properties/system.prop
TARGET_VENDOR_PROP += $(DEVICE_PATH)/configs/properties/vendor.prop

# SELinux
include device/mediatek/sepolicy_vndr/SEPolicy.mk
SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS += $(DEVICE_PATH)/sepolicy/private
SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS += $(DEVICE_PATH)/sepolicy/public
BOARD_VENDOR_SEPOLICY_DIRS += $(DEVICE_PATH)/sepolicy/vendor

# Hardware
# BOARD_HAS_MTK_HARDWARE gates hardware/mediatek/Android.mk (without it the
# wlan tree is never descended into and frameworks/opt/net/wifi fails on a
# missing libwifi-hal-mt66xx). The soong-side modules resolve regardless.
BOARD_HAS_MTK_HARDWARE := true
BOARD_HAVE_BLUETOOTH := true
BOARD_WLAN_DEVICE := MediaTek
# WPA_SUPPLICANT_VERSION et al are deliberately ABSENT (option B): stock's
# A12 wpa_supplicant/hostapd ship in the blobs, and building the source
# daemons against a v31 vendor namespace is the two-libutils condition
# relocated into Wi-Fi (RS4 mechanism; Advan vendor is likewise v31).
# The framework selects HIDL at runtime when no AIDL service is declared,
# so stock's HIDL VINTF fragments must ship with the daemons (Phase 2/3).

# Inherit the proprietary blob makefiles
include vendor/advan/6781/BoardConfigVendor.mk
